### ISSUE TITLE
wifi AP storage issues

### ISSUE THREAD

**Issue by RocketGod-git** [ElectronicCats/Minino#6]
After attempting to delete index 0 while 0 and 1 were stored, the index seems confused:

minino> list
I (460844) cmd_wifi_show_aps: Saved APs: 4
W (460844) cmd_wifi_show_aps: Error getting AP
Command returned non-zero  err code: 0x1 (ERROR)
minino> delete 3
I (499020) cmd_wifi_delete_crendentials: Deleted AP CobraKai
minino> delete 2
I (503096) cmd_wifi_delete_crendentials: Deleted AP CobraKai
minino> delete 1
W (507582) cmd_wifi_delete_crendentials: Error getting AP
Command returned non-zero  err code: 0x45 (ERROR)
minino> delete 0
W (510628) cmd_wifi_delete_crendentials: Error getting AP
Command returned non-zero  err code: 0x45 (ERROR)
minino> list
I (512325) cmd_wifi_show_aps: Saved APs: 2
W (512325) cmd_wifi_show_aps: Error getting AP
Command returned non-zero  err code: 0x1 (ERROR)
minino>

Any tips besides reflashing firmware?

**Comment by Eric286** [comment]
Hello @RocketGod-git 

On the Minino please go to settings - system - wifi, and tell me if your saved network appears here.

I recommend you to flash the device again, but before doing so please go to the About - Version section and tell me what version appears on the device.

Have a nice day!

**Comment by RocketGod-git** [comment]
Nothing is showing there besides the exit menu selection. I'll reflash. Thanks for responding!
